# Generated by Django 3.2.5 on 2021-07-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=400)),
                ('pincode', models.CharField(max_length=6)),
                ('image1', models.ImageField(null=True, upload_to='media/sites')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='media/sites')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='media/sites')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='media/sites')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='media/sites')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='media/sites')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='media/sites')),
            ],
        ),
    ]
