# Generated by Django 3.2.5 on 2021-08-10 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_services_brief'),
    ]

    operations = [
        migrations.CreateModel(
            name='AncilServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brief', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/ancilServices')),
            ],
        ),
    ]
