# Generated by Django 3.2.5 on 2021-08-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_services_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='available',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
