# Generated by Django 3.2.5 on 2021-08-14 04:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='sites',
            name='n_approved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='n_customers',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='n_hours_stayed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='n_projects',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='n_reviews',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='n_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), default=['Air Conditioned', 'TV with DTH', 'Study Table', 'Heated water', 'Fresh Linen and Toiletries', 'Meals', 'Parking space', 'Kithcen', 'Housekeeping'], size=15),
        ),
        migrations.AddField(
            model_name='sites',
            name='n_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sites',
            name='tagline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
