# Generated by Django 3.2.5 on 2021-08-14 05:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210814_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='n_services',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), default=['Air-Conditioned', 'TV-DTH', 'Study-Table', 'Heated-water', 'Toiletries', 'Meals', 'Parking', 'Kithcen', 'Housekeeping'], size=15),
        ),
    ]
