# Generated by Django 3.2.5 on 2021-08-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210818_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/services'),
        ),
        migrations.AddField(
            model_name='services',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/services'),
        ),
        migrations.AddField(
            model_name='services',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/services'),
        ),
        migrations.AddField(
            model_name='services',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='media/services'),
        ),
    ]
